// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Use a direct connection for schema changes and a pooled runtime URL in
    // serverless environments. Local development can use DATABASE_URL alone.
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
